name: Build, test, and publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test rake-db
        working-directory: packages/rake-db
        run: pnpm test
      - name: Test orchid-orm-schema-to-zod
        working-directory: packages/schema-to-zod
        run: pnpm test
