name: tests
on: push
env:
  DATABASE_URL: postgres://postgres:password@localhost:5432/orchid-orm
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Create database
        working-directory: packages/rake-db
        run: pnpm run db create
      - name: Run migrations
        working-directory: packages/rake-db
        run: pnpm run db migrate
      - name: Test pqb
        working-directory: packages/pqb
        run: pnpm test
      - name: Test orchid-orm
        working-directory: packages/orm
        run: pnpm test
      - name: Test rake-db
        working-directory: packages/rake-db
        run: pnpm test
      - name: Test orchid-orm-schema-to-zod
        working-directory: packages/schema-to-zod
        run: pnpm test
      - name: Test orchid-orm-test-factory
        working-directory: packages/test-factory
        run: pnpm test
      - run: echo 42 > coverage-percent.tx
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-percent
          path: coverage-percent.txt
